<?php
/** @var \Memi\Component\Memipilates\Administrator\View\Attendance\HtmlView $this */
defined('_JEXEC') or die;

use Joomla\CMS\Language\Text;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Session\Session;

$escape = static fn (mixed $value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$filterUrl = $escape(Route::_('index.php?option=com_memipilates&view=attendance', false));
$token = $escape(Session::getFormToken());
?>
<div class="container-fluid memi-admin-attendance">
    <h1><?= $escape($this->label('COM_MEMIPILATES_SUBMENU_ATTENDANCE', 'Attendance')); ?></h1>
    <?php if ($this->canManualCheckIn) : ?>
        <section class="card mb-4" aria-labelledby="memi-manual-check-in"><div class="card-header"><h2 class="h5 mb-0" id="memi-manual-check-in"><?= $escape($this->label('COM_MEMIPILATES_ADMIN_MANUAL_CHECK_IN', 'Manual check-in')); ?></h2></div><div class="table-responsive"><table class="table table-striped mb-0"><thead><tr><th><?= $escape($this->label('COM_MEMIPILATES_ADMIN_CUSTOMER', 'Customer')); ?></th><th><?= $escape($this->label('COM_MEMIPILATES_ADMIN_SESSION', 'Session')); ?></th><th><?= $escape($this->label('COM_MEMIPILATES_ADMIN_STARTS_AT', 'Starts')); ?></th><th><?= $escape($this->label('COM_MEMIPILATES_ADMIN_ACTIONS', 'Actions')); ?></th></tr></thead><tbody>
            <?php foreach ($this->checkInCandidates as $candidate) : ?><tr><td><strong><?= $escape($candidate['customer_name'] ?? ''); ?></strong><br><small><?= $escape($candidate['customer_email'] ?? ''); ?></small></td><td><?= $escape($candidate['course_title'] ?? ''); ?></td><td><?= $escape($this->formatDate((string) ($candidate['starts_at'] ?? ''))); ?></td><td><form action="<?= $filterUrl; ?>" method="post" class="d-inline"><input type="hidden" name="option" value="com_memipilates"><input type="hidden" name="task" value="display.manualCheckIn"><input type="hidden" name="booking_id" value="<?= (int) $candidate['booking_id']; ?>"><input type="hidden" name="<?= $token; ?>" value="1"><button class="btn btn-sm btn-primary" type="submit"><?= $escape($this->label('COM_MEMIPILATES_ADMIN_ACTION_CHECK_IN', 'Check in')); ?></button></form></td></tr><?php endforeach; ?>
            <?php if ($this->checkInCandidates === []) : ?><tr><td colspan="4" class="text-muted"><?= $escape($this->label('COM_MEMIPILATES_ADMIN_NO_CHECK_IN_CANDIDATES', 'No customers are currently eligible for manual check-in.')); ?></td></tr><?php endif; ?>
        </tbody></table></div></section>
    <?php endif; ?>
    <form action="<?= $filterUrl; ?>" method="get" class="row g-3 align-items-end mb-3"><input type="hidden" name="option" value="com_memipilates"><input type="hidden" name="view" value="attendance"><div class="col-12 col-md-4"><label class="form-label" for="filter-search"><?= $escape($this->label('COM_MEMIPILATES_ADMIN_FILTER_SEARCH', 'Search')); ?></label><input class="form-control" id="filter-search" name="filter_search" value="<?= $escape($this->filterSearch); ?>" type="search"></div><div class="col-12 col-md-3"><label class="form-label" for="filter-date"><?= $escape($this->label('COM_MEMIPILATES_ADMIN_FILTER_DATE', 'Date')); ?></label><input class="form-control" id="filter-date" name="filter_date" value="<?= $escape($this->filterDate); ?>" type="date"></div><div class="col-12 col-md-3"><label class="form-label" for="filter-status"><?= $escape($this->label('COM_MEMIPILATES_ADMIN_FILTER_STATUS', 'Status')); ?></label><select class="form-select" id="filter-status" name="filter_status"><option value=""><?= $escape(Text::_('JALL')); ?></option><?php foreach ($this->statuses as $status) : ?><option value="<?= $escape($status); ?>"<?= $this->filterStatus === $status ? ' selected' : ''; ?>><?= $escape($this->statusLabel($status)); ?></option><?php endforeach; ?></select></div><div class="col-12 col-md-2 d-flex gap-2"><button class="btn btn-primary" type="submit"><?= $escape($this->label('COM_MEMIPILATES_ADMIN_FILTER_APPLY', 'Filter')); ?></button><a class="btn btn-outline-secondary" href="<?= $filterUrl; ?>"><?= $escape($this->label('COM_MEMIPILATES_ADMIN_FILTER_RESET', 'Reset')); ?></a></div></form>
    <div class="table-responsive"><table class="table table-striped table-hover align-middle"><thead><tr><th><?= $escape(Text::_('JGRID_HEADING_ID')); ?></th><th><?= $escape($this->label('COM_MEMIPILATES_ADMIN_CUSTOMER', 'Customer')); ?></th><th><?= $escape($this->label('COM_MEMIPILATES_ADMIN_SESSION', 'Session')); ?></th><th><?= $escape($this->label('COM_MEMIPILATES_ADMIN_METHOD', 'Method')); ?></th><th><?= $escape($this->label('COM_MEMIPILATES_ADMIN_CHECKED_IN_AT', 'Checked in')); ?></th><th><?= $escape($this->label('COM_MEMIPILATES_ADMIN_SCANNED_BY', 'Scanned by')); ?></th><th><?= $escape(Text::_('JSTATUS')); ?></th><th><?= $escape($this->label('COM_MEMIPILATES_ADMIN_ACTIONS', 'Actions')); ?></th></tr></thead><tbody>
        <?php foreach ($this->items as $item) : ?><tr><td><?= (int) $item['id']; ?></td><td><strong><?= $escape($item['customer_name'] ?? ''); ?></strong><br><small><?= $escape($item['customer_email'] ?? ''); ?></small></td><td><strong><?= $escape($item['course_title'] ?? ''); ?></strong><br><small><?= $escape($this->formatDate((string) ($item['starts_at'] ?? ''))); ?></small></td><td><?= $escape($item['method'] ?? ''); ?></td><td><?= $escape($this->formatDate((string) ($item['checked_in_at'] ?? ''))); ?></td><td><?= $escape($item['scanner_name'] ?? ''); ?></td><td><?= $escape($this->statusLabel((string) ($item['status'] ?? ''))); ?></td><td><?php if ($this->canUndo && (string) ($item['status'] ?? '') === 'confirmed') : ?><form action="<?= $filterUrl; ?>" method="post" class="d-inline"><input type="hidden" name="option" value="com_memipilates"><input type="hidden" name="task" value="display.undoAttendance"><input type="hidden" name="id" value="<?= (int) $item['id']; ?>"><input type="hidden" name="<?= $token; ?>" value="1"><button class="btn btn-sm btn-outline-danger" type="submit"><?= $escape($this->label('COM_MEMIPILATES_ADMIN_ACTION_UNDO_ATTENDANCE', 'Undo')); ?></button></form><?php endif; ?></td></tr><?php endforeach; ?>
        <?php if ($this->items === []) : ?><tr><td colspan="8" class="text-muted"><?= $escape($this->label('COM_MEMIPILATES_ADMIN_NO_RESULTS', 'No records found.')); ?></td></tr><?php endif; ?>
    </tbody></table></div>
    <?php if ($this->paginationLinks() !== '') : ?><nav class="mt-3" aria-label="<?= $escape($this->label('COM_MEMIPILATES_ADMIN_PAGINATION', 'Pagination')); ?>"><?= $this->paginationLinks(); ?></nav><?php endif; ?>
</div>
